/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Launcher */

#ifndef _Included_Launcher
#define _Included_Launcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Launcher
 * Method:    runVim
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Launcher_runVim
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
